algoritmo "Exercicio_16"
// Função :
// Autor : Gabriel Cavalcante Delfino
// Data : 26/03/2019
// Seção de Declarações 
var
SFixo,SFinal,V,C :real
inicio
// Seção de Comandos
escreval ("Funcionario recebe salario fixo")
escreval ("Digite o Valor de Vendas")
leia(V)
escreval ("Digite o Valor do Salário Fixo")
leia(SFixo)
C <-(V*0.04)
SFinal <- SFixo + C
escreval ("O Saldo Final é:",SFinal)
escreval ("O Valor da Comissão é:",C)


fimalgoritmo
