algoritmo "exercicio_5"
// Função : Multiplicação e Potenciação
// Autor : Gabriel Cavalcante Delfino
// Data : 19/03/2019
// Seção de Declarações 
var
X,N,Resultado :real
inicio
// Seção de Comandos
escreval("Multiplicação e Potenciação de Valores")
escreval("Digite o Valor de X")
leia(X)
escreval("Digite o Valor de N")
leia(N)
Resultado <- Exp(X*N,2)
escreval("O Resultado é:", Resultado)
fimalgoritmo
