algoritmo "Exercicio_17"
// Função :
// Autor : Gabriel Cavalcante Delfino
// Data : 26/03/2019
// Seção de Declarações 
var
P,P1,P2 :real
inicio
// Seção de Comandos
escreval ("Calculo do peso atual do usuario, e 15% de engordamento e 20% de emagrecimento")
escreval ("Digite o seu peso atual")
leia(P)
P1 <- P+(P*0.15)
P2 <- P-(P*0.20)
escreval ("Se você engordar 15%, seu peso será:",P1)
escreval ("Se você emagrecer 20%, seu peso será:",P2)
fimalgoritmo
