algoritmo "area_do_triangulo"
// Função : Area do Triangulo
// Autor :  Gabriel Cavalcante Delfino
// Data : 19/03/2019
// Seção de Declarações 
var

B,H,Resultado: real

inicio
// Seção de Comandos
escreval("Calculo da Área do triângulo")
escreval("Digite o valor da base")
leia(B)
escreval("Digite o valor da altura")
leia(H)
Resultado <- B*H/2
escreval("O resultado é:", Resultado)
 
fimalgoritmo
