algoritmo "exercicio_8"
// Função : Calcular a Idade
// Autor : Gabriel Calvalcante Delfino
// Data : 19/03/2019
// Seção de Declarações 
var
AdN,Aatual,Iatual,IFinal :inteiro
inicio
// Seção de Comandos 
escreval("Calculo de Idade Atual até o Ano que desejar")
escreval("Digite o Ano de Nascimento")
leia(AdN)
escreval("Digite o Ano Atual")
leia(Aatual)
Iatual <- Aatual-AdN
IFinal <- 2050-AdN
escreval("A sua Idade atual é: ",Iatual)
escreval("Sua Idade será em 2050:", IFinal)
fimalgoritmo
